LIBRARY--------->NUMPY [PART-1]

The numpy library in Python is a fundamental package for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. Here are some key aspects of the numpy library:

In [116]:
#imports the numpy library into your Python script or interactive session. After importing numpy, you gain access to all of its functions, classes, and submodules.

import numpy as np

numpy store similar type of datatype items

#You can create a 1D numpy array directly from a Python list using the np.array() function.
Creation of Array 1D

In [117]:
arr = np.array([25,41,63,66,85,74])
arr

array([25, 41, 63, 66, 85, 74])

In [118]:
# use to define the type of array
type(arr)
#ndarray -->>> n dimentional array

numpy.ndarray

In [119]:
# used to find the no. of elements in array
# no. of items
arr.size 


6

In [120]:
# this si same as above--> used to find the length of array
len(arr)

6

In [121]:
#to check the dimention of array
arr.ndim

1

Add one extra float value

In [122]:
arr = np.array([25,41,63,66,85,74,2.01])
arr

array([25.  , 41.  , 63.  , 66.  , 85.  , 74.  ,  2.01])

In [123]:
#Every numpy array has a data type (dtype) that specifies the type of elements stored in the array. 
arr.dtype

dtype('float64')

In [124]:
# Used to find the version of numpy which is installed in your system
print(np.__version__)

2.0.0


Add one extra String value, boolean value

In [125]:
arr = np.array([25,41,63,66,85,74,2.01,'krati',True])
arr

array(['25', '41', '63', '66', '85', '74', '2.01', 'krati', 'True'],
      dtype='<U32')

In [126]:
arr.dtype

dtype('<U32')

In [127]:
ls = [25,41,63,66,85,74]
arr = np.array(ls)
arr

array([25, 41, 63, 66, 85, 74])

In [128]:
#Used to access the last element of Array
arr[-1]

np.int64(74)

arr[start:end]: Returns elements starting from index start up to, but not including, index end.

In [129]:
# arr[2:4] refers to slicing an array arr to extract elements from index 2 up to, but not including, index 4. 
arr[2:4]

array([63, 66])

In [130]:
# arr[2:] is a slicing operation that retrieves elements from index 2 to the end of the array arr.
arr[2:]

array([63, 66, 85, 74])

In [131]:
#arr[:4] is a slicing operation that retrieves elements from the beginning of the array arr up to, but not including, index 4.
arr[:4]

array([25, 41, 63, 66])

In [132]:
#arr[start:end:step]: Returns elements starting from index start up to, but not including, index end, with a step size of step.
#arr[::] in numpy creates a shallow copy of the entire array arr, returning all elements in the same order.
arr[::]  #starting--> 0,  stoping--> end, jump-->1

array([25, 41, 63, 66, 85, 74])

In [133]:
arr[-1] = 500

In [134]:
arr

array([ 25,  41,  63,  66,  85, 500])

In [135]:
#performing arr + 2 is a basic arithmetic operation that adds the scalar value 2 to each element in the numpy array arr.
arr + 2

array([ 27,  43,  65,  68,  87, 502])

In [136]:
#arr * 2 will multiply each element of the array arr by 2.
arr*2

array([  50,   82,  126,  132,  170, 1000])

Creation of 2D array
You can create a 2D array by passing a nested list to numpy.array:



In [137]:
#The variable ls represents a nested list in Python:
ls = [[1,2,3],[4,5,6],[7,8,9]]

In [138]:
#This will display the nested list ls as it is defined. Each sublist corresponds to a row in the 2D structure.
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [139]:
# Used to check the type of list elements
type(ls)

list

In [140]:
#ls[0] gives you the first sublist [1, 2, 3] from the nested list ls.
ls[0]

[1, 2, 3]

In [141]:
#ls[-1] gives you the last sublist [7, 8, 9] from the nested list ls.
ls[-1]

[7, 8, 9]

In [142]:
#ls[0][1] accesses the element at index 1 within the sublist ls[0].
ls[0][1]  #ls[0,1]

2

In [143]:
# convert the nested list ls into a NumPy array using np.array(ls) & assign to arr2
arr2 = np.array(ls)

In [144]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
#The ndim attribute in NumPy arrays returns the number of dimensions (or axes) of the array. For a 2D array, it will return 2.
arr2.ndim

2

In [146]:
#The shape attribute in NumPy arrays returns a tuple that represents the size of each dimension of the array. For a 2D array (matrix), the shape tuple will have two elements: the number of rows and the number of columns.
arr2.shape

(3, 3)

In [147]:
arr2[1]

array([4, 5, 6])

In [148]:
#The slice 0:2 selects rows from index 0 to 1 (exclusive of index 2), which gives us the first two rows of arr2.
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
#arr2[1][1:] further slices the second row (arr2[1]), starting from index 1 to the end. In this case, it selects elements [5, 6] from the second row [4, 5, 6].
arr2[1][1:]
# or
#arr2[1,1:]

array([5, 6])

In [150]:
arr2[1:,1:]

array([[5, 6],
       [8, 9]])

In [151]:
#result contains the subarray starting from the second-to-last row and second-to-last column of arr2, which includes elements [5, 6] and [8, 9]
arr2[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [152]:
# Print the modified array
arr2[2,2]=90

In [153]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

Built-in function

In [154]:
# Generate a NumPy array with 500 random integers between 1 and 199
arr = np.random.randint(1,200,500)# 500-> no. of items, 1,200-> in b/w 1 to 200
arr # single d array

array([170, 143, 135,  32, 135,  48, 183,  92,   1,  12, 126,  17, 127,
        45, 150, 168,   1,  77,  36,  72,  36,  31,  41, 148, 100,  36,
        73, 197, 194,  81, 116,  90, 125, 117,   7, 127, 157, 175,  81,
       175, 145, 198, 120,  22,  23,   9, 122,  97,  88, 155, 169,  22,
        53, 186, 146, 167,  45, 141, 189,  16,  94,   7, 141, 108, 194,
        86,  71,  43,   6, 164, 110, 104,  88,  12,  74,  33, 157,  62,
       100,  44,  23, 198, 119,  67,   7, 147, 114,  69, 195, 163, 169,
       197,  11,  76,  92, 127,  13, 197,  79,  22,  70, 150,  83,   8,
        11, 170,  93, 126, 138, 165, 156,  60,  99,  26, 150, 170,  41,
        37, 174,  52, 154,  37,  79,  26,  66, 177,  60,  80,  15,  59,
       130,  10,  76, 189, 137, 116, 144,  23,   2, 194,  42,  70,  47,
        10, 100,  81, 188,  87, 146, 129, 104,   5, 117,   4,  66,  68,
       103,  41,  37,  54,  45,   3,   2, 149, 101, 171,  44,  52, 141,
        88, 129,  86, 164, 136, 160,  89,  92, 142, 155, 137, 18

How many items are less than 100

In [155]:
c=0
for i in arr:
    if(i<100):
        c=c+1
print(c)        

268


In [156]:
# Count elements less than or equal to 100
arr[arr<=100].size

271

OR

In [157]:
len(arr[arr<=100])

271

In [158]:
#filtered_arr.shape retrieves the shape of the resulting filtered array.
arr[arr<=100].shape

(271,)

In [159]:
## Generate a NumPy array with shape (10, 6) containing random integers between 1 and 199
arr2 = np.random.randint(1,200,(10,6)) # 10-> row, 5-> col
arr2

array([[ 41, 151,  86,  68, 152,  24],
       [ 49,  13, 143, 104,  35,   6],
       [ 53, 153,  85, 137, 180,  25],
       [190, 172,   8, 139,  89,  68],
       [156,  40, 101, 169,  57, 198],
       [ 83, 153, 139,  19, 191,  38],
       [106, 106,  59,  63,  57,  44],
       [125, 107, 141, 199, 172, 144],
       [195,  45, 107,  82, 118,  21],
       [ 97,   7,  99,  45, 148, 142]], dtype=int32)

In [160]:
## Create a NumPy array with 10 elements initialized to zero
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [161]:
arr.dtype

dtype('float64')

In [162]:
# Create a NumPy array with shape (10, 5) initialized to zeros
arr = np.zeros((10,5)) #2D array
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [163]:
# Create a NumPy array with 10 elements initialized to one
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [164]:
arr = np.ones((10,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [165]:
ls = [1,2,3,4,5,6,7,8,9]
ls

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [166]:
#The code ls = list(range(10)) creates a Python list ls containing integers from 0 to 9.
ls = list(range(10))
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [167]:
#np.arange(10) creates a NumPy array that starts at 0 and stops before 10,
np.arange(10) #create single dimentional array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
#np.arange(5, 100) creates a NumPy array that starts at 5 and stops before 100, resulting in elements from 5 up to 99.
np.arange(5,100)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [169]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
arr = np.arange(60)
arr #single dimentional array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [171]:
# 2D , 60
# 10,6

## Reshape the array into a 10x6 matrix
arr.reshape(10,6)  #  10 * 6 = 60

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [172]:
arr.reshape(10,7)

ValueError: cannot reshape array of size 60 into shape (10,7)

In [ ]:
arr.reshape(3,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])

In [ ]:
arr = arr.reshape(10,6)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

creation of 3D array

In [ ]:
arr1 = [1,2,3]
arr2 = [[1,2,3],[1,2,3],[1,2,3]] #[2d,2d,2d]
arr3 = [[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]

In [ ]:
arr = np.array(arr3)
arr

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [ ]:
#Check the dimention
arr.ndim

3

In [ ]:
# Generate a 3D array with shape (3, 5, 3) filled with random integers between 1 and 199
arr3 = np.random.randint(1,200,(3,5,3)) #table row col
arr3

array([[[ 94, 127,  14],
        [ 63,  46,  79],
        [ 91,  19, 184],
        [ 92, 163, 191],
        [ 79, 130, 174]],

       [[110,  56, 176],
        [ 36,  26,  28],
        [193, 146,  68],
        [118,  79,  85],
        [ 89, 173,  57]],

       [[185,  48, 156],
        [174, 172,  49],
        [ 63, 188, 129],
        [187,  36, 158],
        [ 30,  79, 190]]], dtype=int32)

In [ ]:
# Print the shape of the array
arr3.shape

(3, 5, 3)

In [ ]:
#arr3[1, 4, 0:] accesses a specific subset of arr3:
#1: Selects the second matrix (indexing starts at 0).
#4: Selects the fifth row within the selected matrix.
#0:: Selects all elements starting from the first column (index 0) to the end of the row.

arr3[1,4,0:]

array([ 89, 173,  57], dtype=int32)

In [ ]:
arr3[2,0:2,1:]

array([[ 48, 156],
       [172,  49]], dtype=int32)

or

In [ ]:
arr3[:,0,:]

array([[ 94, 127,  14],
       [110,  56, 176],
       [185,  48, 156]], dtype=int32)

OR

In [ ]:
#arr3[:, -5, :] accesses a specific subset of arr3:
#:: Selects all matrices (pages) along the first dimension.
#-5: Selects the fifth row from the end along the second dimension (5 is the total number of rows, so -5 selects the first row).
#:: Selects all elements along the third dimension.

arr3[:,-5,:]

array([[ 94, 127,  14],
       [110,  56, 176],
       [185,  48, 156]], dtype=int32)

In [ ]:
arr = np.array([9,7,8])
arr

array([9, 7, 8])

In [ ]:
# Find the minimum value in arr

min(arr)

np.int64(7)

In [ ]:
## Find the maximum value in arr
max(arr)

np.int64(9)

In [ ]:
mean(arr)

NameError: name 'mean' is not defined

In [ ]:
# Find the average value in arr
np.mean(arr)  

np.float64(8.0)

In [ ]:
np.sum(arr)

np.int64(24)

In [ ]:
arr

array([9, 7, 8])

In [ ]:
## Find the index of the minimum value
np.argmin(arr)  # return index of min item

np.int64(1)

In [ ]:
# Find the index of the minimum value
np.argmax(arr)

np.int64(0)

In [ ]:
arr.sort() # by default sort in asc. order

In [ ]:
arr

array([7, 8, 9])

In [ ]:
arr[::-1]  # sort in des. order

array([9, 8, 7])