In [220]:
import numpy as np

numpy store similar type of datatype items

Creation of Array 1D

In [221]:
arr = np.array([25,41,63,66,85,74])
arr

array([25, 41, 63, 66, 85, 74])

In [222]:
type(arr)
#ndarray -->>> n dimentional array

numpy.ndarray

In [223]:
arr.size # no. of items

6

In [224]:
len(arr)

6

In [225]:
arr.ndim #to check the dimention of array

1

Add one extra float value

In [226]:
arr = np.array([25,41,63,66,85,74,2.01])
arr

array([25.  , 41.  , 63.  , 66.  , 85.  , 74.  ,  2.01])

In [227]:
arr.dtype

dtype('float64')

In [228]:
print(np.__version__)

2.0.0


Add one extra String value, boolean value

In [229]:
arr = np.array([25,41,63,66,85,74,2.01,'krati',True])
arr

array(['25', '41', '63', '66', '85', '74', '2.01', 'krati', 'True'],
      dtype='<U32')

In [230]:
arr.dtype

dtype('<U32')

In [231]:
ls = [25,41,63,66,85,74]
arr = np.array(ls)
arr

array([25, 41, 63, 66, 85, 74])

In [232]:
arr[-1]

np.int64(74)

In [233]:
arr[2:4]

array([63, 66])

In [234]:
arr[2:]

array([63, 66, 85, 74])

In [235]:
arr[:4]

array([25, 41, 63, 66])

In [236]:
arr[::]  #starting--> 0,  stoping--> end, jump-->1

array([25, 41, 63, 66, 85, 74])

In [237]:
arr[-1] = 500

In [238]:
arr

array([ 25,  41,  63,  66,  85, 500])

In [239]:
arr + 2

array([ 27,  43,  65,  68,  87, 502])

In [240]:
arr*2

array([  50,   82,  126,  132,  170, 1000])

Creation of 2D array

In [241]:
ls = [[1,2,3],[4,5,6],[7,8,9]]

In [242]:
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [243]:
type(ls)

list

In [244]:
ls[0]

[1, 2, 3]

In [245]:
ls[-1]

[7, 8, 9]

In [246]:
ls[0][1]  #ls[0,1]

2

In [247]:
arr2 = np.array(ls)

In [248]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [249]:
arr2.ndim

2

In [250]:
arr2.shape

(3, 3)

In [251]:
arr2[1]

array([4, 5, 6])

In [252]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [253]:
arr2[1][1:]
# or
#arr2[1,1:]

array([5, 6])

In [254]:
arr2[1:,1:]

array([[5, 6],
       [8, 9]])

In [255]:
arr2[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [256]:
arr2[2,2]=90

In [257]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

Built-in function

In [258]:
arr = np.random.randint(1,200,500)# 500-> no. of items, 1,200-> in b/w 1 to 200
arr # single d array

array([155,  52,  93, 151,  37, 127, 189, 122,   3,  46, 168, 102, 114,
        99,  32,  12,   5,  47,  64, 177, 143, 184,  69, 178, 199, 164,
        95, 183, 113, 110,  46,  84, 197, 162,  39,  47, 100,  93, 121,
        92, 160,  45,   4, 157,  79, 104, 196, 126,  71,  92,   4,  58,
       193,  16,   6, 127,  99,  40,  91, 116,  12,  63, 162, 109, 114,
       176,  51,  26, 166,  16, 106, 124,   3,  80, 193,  97,  28,  10,
        82, 184, 128,  71,  11, 195, 189,  30,  40, 196, 153,  84, 158,
       159,  40, 185,  27, 117, 168, 102,  50,  68, 118, 116, 101, 160,
        53,  93,   6, 114, 147, 197, 159,   6,  14, 143,  66,  25,  16,
       114, 166, 161, 149, 115, 159,  46,  24,  76, 141, 127,  62, 165,
        45,  11,  88,  96, 133, 168, 160,  87,   5,  24, 108,  86, 123,
       153, 130, 101,  77, 171,  19, 112,  76,  27, 155,  62, 168, 155,
        76,  21,  94, 113, 167,  75, 178,  12,  93,  42, 170, 197,  73,
        15,  29,  52,  64, 107,  84, 196, 192,  38,  25, 177, 14

How many items are lss than 100

In [259]:
c=0
for i in arr:
    if(i<100):
        c=c+1
print(c)        

260


In [260]:
arr[arr<=100].size

264

OR

In [261]:
len(arr[arr<=100])

264

In [262]:
arr[arr<=100].shape

(264,)

In [263]:
arr2 = np.random.randint(1,200,(10,6)) # 10-> row, 5-> col
arr2

array([[105,  30, 124, 159,  67,  48],
       [ 30, 165, 180,  98,  29, 195],
       [120, 180,   4, 137, 150, 198],
       [166, 165, 135,   4,  47, 195],
       [185, 144, 143,  27,  79,  26],
       [ 89,  78,  86, 198, 178,  21],
       [166,   7, 150,  24,  99, 126],
       [153,  27,  41,  40,  67,  18],
       [ 91,  86, 133, 115, 195, 196],
       [160, 177, 125,  22,  54,  29]], dtype=int32)

In [264]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [265]:
arr.dtype

dtype('float64')

In [266]:
arr = np.zeros((10,5)) #2D array
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [267]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [268]:
arr = np.ones((10,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [269]:
ls = [1,2,3,4,5,6,7,8,9]
ls

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [270]:
ls = list(range(10))
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [271]:
np.arange(10) #create single dimentional array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [272]:
np.arange(5,100)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [273]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [274]:
arr = np.arange(60)
arr #single dimentional array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [275]:
# 2D , 60
# 10,6

arr.reshape(10,6)  #  10 * 6 = 60

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [276]:
arr.reshape(10,7)

ValueError: cannot reshape array of size 60 into shape (10,7)

In [ ]:
arr.reshape(3,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])

In [ ]:
arr = arr.reshape(10,6)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

creation of 3D array

In [ ]:
arr1 = [1,2,3]
arr2 = [[1,2,3],[1,2,3],[1,2,3]] #[2d,2d,2d]
arr3 = [[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]

In [ ]:
arr = np.array(arr3)
arr

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [ ]:
arr.ndim

3

In [ ]:
arr3 = np.random.randint(1,200,(3,5,3)) #table row col
arr3

array([[[ 94, 127,  14],
        [ 63,  46,  79],
        [ 91,  19, 184],
        [ 92, 163, 191],
        [ 79, 130, 174]],

       [[110,  56, 176],
        [ 36,  26,  28],
        [193, 146,  68],
        [118,  79,  85],
        [ 89, 173,  57]],

       [[185,  48, 156],
        [174, 172,  49],
        [ 63, 188, 129],
        [187,  36, 158],
        [ 30,  79, 190]]], dtype=int32)

In [ ]:
arr3.shape

(3, 5, 3)

In [ ]:
arr3[1,4,0:]

array([ 89, 173,  57], dtype=int32)

In [ ]:
arr3[2,0:2,1:]

array([[ 48, 156],
       [172,  49]], dtype=int32)

or

In [ ]:
arr3[:,0,:]

array([[ 94, 127,  14],
       [110,  56, 176],
       [185,  48, 156]], dtype=int32)

OR

In [ ]:
arr3[:,-5,:]

array([[ 94, 127,  14],
       [110,  56, 176],
       [185,  48, 156]], dtype=int32)

In [ ]:
arr = np.array([9,7,8])
arr

array([9, 7, 8])

In [ ]:
min(arr)

np.int64(7)

In [ ]:
max(arr)

np.int64(9)

In [ ]:
mean(arr)

NameError: name 'mean' is not defined

In [ ]:
np.mean(arr)  #average

np.float64(8.0)

In [ ]:
np.sum(arr)

np.int64(24)

In [ ]:
arr

array([9, 7, 8])

In [ ]:
np.argmin(arr)  # return index of min item

np.int64(1)

In [ ]:
np.argmax(arr)

np.int64(0)

In [ ]:
arr.sort() # by default sort in asc. order

In [ ]:
arr

array([7, 8, 9])

In [ ]:
arr[::-1]  # sort in des. order

array([9, 8, 7])

TypeError: 'type' object cannot be interpreted as an integer